### ISSUE TITLE
Android is not supported

### ISSUE THREAD

**Issue by danarth** [UniNinja/mobile#2]
At the moment it looks like only iOS is supported. Is there a build command we can run that allows us to build the Android version also?

**Comment by LoicVerrall** [comment]
Yep, sorting this out this morning!

**Comment by danarth** [comment]
@LoicVerrall does your recent PR #6 support Android?

**Comment by LoicVerrall** [comment]
Bear with me, just need to add the Android platform tools to my class path 🙄🤓😂

**Comment by LoicVerrall** [comment]
<img width="483" alt="screen shot 2018-03-15 at 16 24 50" src="https://user-images.githubusercontent.com/17081120/37476575-688ca450-286d-11e8-969f-8c70438607bb.png">
Can confirm Android is now working ☺️

**Comment by danarth** [comment]
Okay. If you could double check that it works on Android and add another commit to your PR #6 and it should be good to go. In your new commit message (or on PR thread) be sure to reference this issue #2

Thanks 🤙
