### ISSUE TITLE
Configure CI tools

### ISSUE THREAD

**Issue by danarth** [UniNinja/mobile#3]
According to GitHub, the build currently fails because a `.travis.yml` file has not been written. We should aim to get this file written asap to allow us to properly use continuous integration.

**Comment by danarth** [comment]
### Update
We should consider using [Fastlane](https://fastlane.tools) to help use use CI to push our app to the individual app stores.

### Next steps
It would be great if we could research Fastlane and attempt to get it working with our project by the end of next week. I have assigned the entire ESRS team to this issue so that each member can research Fastlane and how we can implement it.

**Comment by Tang-1996** [comment]
Been reading through the 'fastlane' documentation for ios, heres a link to the guide:
https://docs.fastlane.tools/getting-started/ios/setup/
